# Generated by Django 4.2.11 on 2024-05-09 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('scoring_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评分ID')),
                ('level', models.CharField(default='A', max_length=50, verbose_name='等级')),
                ('description', models.TextField(default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': '评分标准',
                'verbose_name_plural': '评分标准 Scoring',
            },
        ),
        migrations.CreateModel(
            name='ChallengeRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='闯关记录ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('result', models.CharField(default='未完成', max_length=50, verbose_name='闯关结果')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level', verbose_name='关卡')),
                ('scoring_standard', models.ManyToManyField(to='feedback.scoring', verbose_name='评分标准')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '闯关记录',
                'verbose_name_plural': '闯关记录 ChallengeRecord',
            },
        ),
    ]
