# Generated by Django 4.2.11 on 2024-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='details',
            field=models.TextField(blank=True, default='', null=True, verbose_name='详情'),
        ),
        migrations.AddField(
            model_name='scoring',
            name='score_range',
            field=models.CharField(default='0-100', max_length=50, verbose_name='分数区间'),
        ),
        migrations.AlterField(
            model_name='scoring',
            name='description',
            field=models.CharField(max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='scoring',
            name='level',
            field=models.CharField(max_length=50, verbose_name='等级'),
        ),
    ]
