# Generated by Django 4.2.11 on 2024-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_scoring_details_scoring_score_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='score_range',
            field=models.CharField(default='90-100', max_length=50, verbose_name='分数区间'),
        ),
    ]
