# Generated by Django 4.2.11 on 2024-05-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_scoring_score_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengerecord',
            name='answer',
            field=models.CharField(default='', max_length=128, verbose_name='用户答案'),
        ),
    ]
