# Generated by Django 4.2.11 on 2024-05-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('feedback', '0004_challengerecord_answer'),
    ]
    operations = [


        migrations.AddField(
            model_name='challengerecord',
            name='scoring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.scoring',
                                    verbose_name='评分标准'),
        ),
    ]
