# Generated by Django 4.2.11 on 2024-05-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False, verbose_name='勋章ID')),
                ('name', models.CharField(default='未命名勋章', max_length=100, verbose_name='名称')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('acquired_count', models.IntegerField(default=0, verbose_name='获得人数')),
            ],
            options={
                'verbose_name': '勋章信息',
                'verbose_name_plural': '勋章信息 Badge',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关卡ID')),
                ('level_name', models.CharField(default='未命名关卡', max_length=100, verbose_name='关卡名称')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('difficulty', models.CharField(default='简单', max_length=50, verbose_name='难度等级')),
                ('score_range', models.CharField(default='0-100', max_length=50, verbose_name='分数区间')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='levels.badge', verbose_name='勋章')),
            ],
            options={
                'verbose_name': '关卡信息',
                'verbose_name_plural': '关卡信息 Level',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学科 ID')),
                ('subject_name', models.CharField(default='未命名学科', max_length=100, verbose_name='学科名')),
                ('learning_modules', models.TextField(default='', verbose_name='学习模块')),
            ],
            options={
                'verbose_name': '学科信息',
                'verbose_name_plural': '学科信息 Subject',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='题目ID')),
                ('content', models.TextField(default='', verbose_name='题目内容')),
                ('answer', models.TextField(default='', verbose_name='答案')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level', verbose_name='关卡')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目信息 Question',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.subject', verbose_name='学科'),
        ),
    ]
