# Generated by Django 4.2.11 on 2024-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_badge_local_link_badge_online_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='local_link',
            field=models.FileField(blank=True, null=True, upload_to='badges/', verbose_name='本地链接'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='online_link',
            field=models.URLField(blank=True, null=True, verbose_name='线上链接'),
        ),
    ]
