# Generated by Django 4.2.11 on 2024-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_badge_content_alter_badge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='', max_length=200, verbose_name='选项A'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='', max_length=200, verbose_name='选项B'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='选项C'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='选项D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=64, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='题目内容'),
        ),
    ]
