# Generated by Django 4.2.11 on 2024-05-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_question_option_a_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(default='', verbose_name='解题思路'),
        ),
    ]
