# Generated by Django 4.2.11 on 2024-05-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_question_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='levels.level', verbose_name='关卡'),
        ),
    ]
