# Generated by Django 4.2.11 on 2024-05-09 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_role_profile_avatar_alter_profile_membership_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gold_count',
            field=models.IntegerField(default=0, verbose_name='金币数'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_level',
            field=models.CharField(default='普通', max_length=50, verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='默认用户', max_length=100, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission_module',
            field=models.CharField(default='default', max_length=128, verbose_name='权限模块'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID'),
        ),
    ]
