# Generated by Django 4.2.11 on 2024-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar_alter_profile_gold_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='common', max_length=64, verbose_name='用户类型'),
        ),
    ]
