# Generated by Django 4.2.11 on 2024-05-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '我的自定义模型名称', 'verbose_name_plural': '我的自定义模型名称们'},
        ),
    ]
