# Generated by Django 4.2.11 on 2024-05-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息 Profile'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色管理', 'verbose_name_plural': '角色管理 Role'},
        ),
    ]
